{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinybusy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinybusy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinybusy/shinybusy_{{ version }}.tar.gz
  sha256: 628360c74cc4d454e88ff622398b30cfb3cd6cdef0515f09b248b6d87a894eae

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-shiny
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-shiny

test:
  commands:
    - $R -e "library('shinybusy')"           # [not win]
    - "\"%R%\" -e \"library('shinybusy')\""  # [win]

about:
  home: https://github.com/dreamRs/shinybusy
  license: GPL-3.0-only
  summary: Add a global indicator (spinner, progress bar, gif) in your 'shiny' applications to show the user that the server is busy.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinybusy
# Title: Busy Indicator for 'Shiny' Applications
# Version: 0.2.0
# Authors@R: c(person("Fanny", "Meyer", email = "fanny.meyer@dreamrs.fr", role = c("aut")), person("Victor", "Perrier", email = "victor.perrier@dreamrs.fr", role = c("aut", "cre")), person("Silex Technologies", comment = "https://www.silex-ip.com", role = "fnd"), person("Tobias", "Ahlin", role = "cph", comment = "SpinKit CSS"), person("Epicmax", role = "cph", comment = "Epic-spinners CSS"), person("Chris", "Antonellis", role = "cph", comment = "freezeframe.js"), person("Jacobo", "Tabernero", role = "cph", comment = "nanobar.js"), person("Kimmo", "Brunfeldt", role = "cph", comment = "progressbar.js"))
# Description: Add a global indicator (spinner, progress bar, gif) in your 'shiny' applications to show the user that the server is busy.
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: htmltools, shiny, jsonlite, htmlwidgets
# RoxygenNote: 6.1.1
# URL: https://github.com/dreamRs/shinybusy
# BugReports: https://github.com/dreamRs/shinybusy/issues
# Suggests: testthat, covr, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-28 23:09:15 UTC; perri
# Author: Fanny Meyer [aut], Victor Perrier [aut, cre], Silex Technologies [fnd] (https://www.silex-ip.com), Tobias Ahlin [cph] (SpinKit CSS), Epicmax [cph] (Epic-spinners CSS), Chris Antonellis [cph] (freezeframe.js), Jacobo Tabernero [cph] (nanobar.js), Kimmo Brunfeldt [cph] (progressbar.js)
# Maintainer: Victor Perrier <victor.perrier@dreamrs.fr>
# Repository: CRAN
# Date/Publication: 2019-10-29 06:30:03 UTC
