travis:
  secure:
    BINSTAR_TOKEN: Wiv6f2zLcGybUJ1wsHjwSTI7XONmHm4M02zI6e8r66SeRp6b7LB61yhX4Cw7xpuTIeIJ17pJbjksztM39b5TaTvnDL+Ewau5VlcCXwEeYbzY/MihBnlMiV+PIczl5dFSRII9PprI3qNPx4S4QEK4P9aoQiwUYuJNyxcbJeDfvKL+pSimdXOwwXX3URsTnYFbGs5RKGE6hw8SdSzJjpUjGGuyHkwKAUD22uzZBPdktSBXo6sT/bzduItoIxtONIirE1faQq/knE9MHgRjGktRUnEpDNPJYN5wMumEDNEN6cqKurk0BuDhawyMAiLanZ78+VbT80KvEixll32q+qYqhVpa4otoJeQzxaHtHpqu25YwxUYGDDrKpnp3KsxfosRlpAbSQQP5Ff2p1w9UgVbifbuXWcnuhzIqZyZDe41j5eQm8KPyFsvVad4PHeks727rX4Ygo4m9JYlXc4rq5aMj7D8UfrlrTgZ7Rs8Cc2FPelT55ib0STSYXeLlSwo0lYWE08Vfse+u0cpAAGJ5rO0bZZQCVXWNFpLV0Q0kOePvgpz3IgP4ZYwtNaCMsavemo+PCPBvAt3x4qXv0LFwwHDwXXiHph9hiwrIP6WD6O4CGhVa1bFgXa6dHLibFuyOne/JcIjKi39dNCZuUDHnr/XVTTC57P88gRHh7R/SFfEyOBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
